# This is a core2go-based application config file example
# with a available properties and example values.

# Common service configs
service:
  name: service_name
  title: Service Name
  version: 0.0.1
  is_debug: false

# Redis connection configs
redis:
  host: 127.0.0.1:6379
  username: user
  password: password
  db: 0

# Postgres connection configs
postgres:
  host: 127.0.0.1:5432
  username: user
  password: password
  db: dbname
  options:
    sslmode: verify-ca
    pool_max_conns: 10
